project:
  type: website

website:
  title: "Ali Siahkoohi"
  google-analytics: "G-VCVVD4KWRF"
  search: false

  # Without this, the page footer will not display. It is removed in index.qmd
  navbar:
    background: dark

  page-footer:
    center:
      - text: "License"
        href: https://raw.githubusercontent.com/alisiahkoohi/alisiahkoohi.github.io/master/LICENSE

format:
  html:
    theme:
      light: lumen
      dark: slate
    fontsize: 0.9em
    mainfont: "sans-serif"
    toc: true
    toc-title: "<br>"
    link-external-newwindow: false
    minimal: true
